version: '3'

services:
  database-h2:
      image: "oscarfonts/h2:latest"
      container_name: h2_db
      ports:
        - ${DB_PORT}:${DB_PORT}
#        - "8081:81"
      environment:
        TZ: Asia/Seoul
        H2_OPTIONS: -ifNotExists
#        MYSQL_ROOT_HOST: root
#        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#        MYSQL_DATABASE: ${DB_NAME}
#        MYSQL_USER: ${DB_USER}
#        MYSQL_PASSWORD: ${DB_PASSWORD}
      volumes:
        - ./h2/:/opt/h2-data
      networks:
        - ticketing_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    container_name: ticketing_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database-h2
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    networks:
      - ticketing_network

networks:
  ticketing_network:
