spring:
#  profiles:
#    active: local
#  config:
##    import:
##      -optional:file: .env[.properties]
#    activate:
#      on-profile: local


  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  datasource:
    url: jdbc:h2:tcp://database-h2:9002/ticketing_db # ${DATASOURCE_URL}
    username: sa # ${DATASOURCE_USER}
    password:  # ${DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver # com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true  # H2 콘솔 활성화 여부
      path: /h2-console  # H2 콘솔 경로

  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: true
