spring:
  profiles:
    active: local
---
service:
    jwt:
      secret-key: my-secret-for-jwt-secret-supposed-tobe-longer-longer-very-long-my-secret-for-jwt-secret-supposed-tobe-longer-longer-very-long-my-secret-for-jwt-secret-supposed-tobe-longer-longer-very-long



spring:
  application:
    name: ticketing
  jwt:
    access-expiration: 300000
  queue:
    num-activation-per-min: 5000
  redis:
    url: "localhost"
    port: 6379
    timeout: 2000

  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: local
  jpa:
    ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    url: 'jdbc:h2:mem:ticketing_db;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false' # jdbc:h2:tcp://localhost/~/ticketing_db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: true

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  datasource:
    url: jdbc:h2:tcp://localhost:9002/ticketing_db
    username: sa
    password:
    driver-class-name: com.mysql.jdbc.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: true



