name: CI Pipeline

on:
  push:
    branches:
      - 'feature*' # TODO: branch naming
  pull_request:
    branches:
      - 'dev'
      - 'main'
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle' # cache 사용
          cache-dependency-path: | # optional
            *.gradle*
            **/gradle-wrapper.properties
      - name: Grant Permission to gradlew
        run: chmod +x gradlew
      - run: ./gradlew build --no-daemon test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            build/test-results/test/*.xml
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Gradle-Package
          path: build/libs

      - name: Publish Sonarlint Results
        uses: jwgmeligmeyling/spotbugs-github-action@v1.2
        with:
          name: Sonarlint
          title: Sonarlint report
          path: build/reports/sonarlint/*.xml

      - name: Publish Spotbugs Results
        uses: jwgmeligmeyling/spotbugs-github-action@v1.2
        with:
          name: Spotbugs
          path: build/reports/spotbugs/*.xml